
### GET ALL
GET http://localhost:3003/product HTTP/1.1
### GET ALL WITH EXCLUDE IDS
GET http://localhost:3003/product?exclude_ids=31&exclude_ids=30&active=1 HTTP/1.1
### GET ALL WITH EXCLUDE ATTRIBUTE VALUE
GET http://localhost:3003/product?is_draft=0 HTTP/1.1
### GET ALL WITH EXCLUDE IDS AND ATTRIBUTE VALUES
GET http://localhost:3003/product?exclude_ids=31&exclude_ids=30&active=1&is_draft=0 HTTP/1.1


### GET BY ID
GET http://localhost:3003/product/id/55 HTTP/1.1

### GET BY NAME
GET http://localhost:3003/product/name/Producto A HTTP/1.1

### GET BY CUSTOMID
GET http://localhost:3003/product/custom_id/ProdA HTTP/1.1

### GET BY SKU
GET http://localhost:3003/product/sku/A12345 HTTP/1.1

### GET BY BARCODE
GET http://localhost:3003/product/barcode/987654321 HTTP/1.1


### CREATE
POST http://localhost:3003/product HTTP/1.1   
Content-Type: application/json

{
  "name": "Prosasdasdsaductsdso Y",
  "type": "Electrónico",
  "description": "Descripción del producto A",
  "sku": "SKUasdsaassdasd1sda2sds345",
  "active": 1,
  "sale_price": 25.16,
  "is_draft": 0
}

### UPDATE
PATCH http://localhost:3003/product/63 HTTP/1.1
Content-Type: application/json

{
  "active": 0
}

### DELETE
DELETE http://localhost:3003/product/34 HTTP/1.1